local path = minetest.get_modpath("worldedit")
dofile(path .. "/manipulations.lua")
dofile(path .. "/primitives.lua")
dofile(path .. "/visualization.lua")
dofile(path .. "/serialization.lua")
dofile(path .. "/code.lua")