name: "Test"
on: [push, pull_request]

jobs:
  test:
    name: "Unit Tests ${{ matrix.cfg.image }}"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        cfg:
          - { image: 'registry.gitlab.com/minetest/minetest/server:5.0.1', mtg: false }
          - { image: 'registry.gitlab.com/minetest/minetest/server:5.5.1', mtg: false }
          - { image: 'ghcr.io/minetest/minetest:5.10.0', mtg: true }
          - { image: 'ghcr.io/luanti-org/luanti:master', mtg: true } # latest git
    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: 'luanti-org/minetest_game'
        path: minetest_game
      if: ${{ matrix.cfg.mtg }}

    - name: Run tests
      run: ./.util/run_tests.sh --docker
      env:
        DOCKER_IMAGE: "${{ matrix.cfg.image }}"
